library(quantmod)
#GNP deflator data
getSymbols("GNPDEF", src= "FRED")
chartSeries(GNPDEF)
head(GNPDEF)
GNPDEF = ts(GNPDEF$GNPDEF, start = 1947, frequency = 4)
head(GNPDEF)
chartSeries(GNPDEF)
logGNP = log(GNPDEF)
chartSeries(logGNP)
logGNP = window(logGNP,start = 1960, end = 2005)
diff1 = diff(logGNP)
plot(diff1)
head(diff1)
#for adf test
library(fUnitRoots)
adfTest(diff1)
diff2 = diff(diff1)
plot(diff2)
adfTest(diff2)
acf(diff2)
pacf(diff2)
chartSeries(GNPDEF, theme = "white")
adfTest(GNPDEF)
chartSeries(diff2)
chartSeries(diff2, theme = "white")
acf(diff2)
library(forecast)
modelfit = ar(diff2)
print(modelfit$aic, digits = 2)
pacf(diff2)
acf(diff2)
Model2 = Arima(GNPDEF, c(4, 2, 1))
Model3 = Arima(GNPDEF, c(2,2,4))
Model4 = Arima(GNPDEF, c(2,2,1))
acf(residuals(Model1))
acf(residuals(Model2))
acf(residuals(Model3))
Box.test(residuals(Model1),lag=12,type="Ljung-Box")
Box.test(residuals(Model3),lag=12,type="Ljung-Box")
Box.test(residuals(Model2),lag=12,type="Ljung-Box")
acf(residuals(Model1))
acf(residuals(Model2))
plot(forecast(Model2, 10))
plot(forecast(Model1, 10))
plot(forecast(Model3, 10))

#Another dataset
getSymbols("GE")
head(GE)
model1 = Arima(GE$GE.Adjusted, c(0,1,0), include.drift = TRUE)
model1
forecast(model1, 20)
plot(forecast(model1, 20))
